[package]
name = "bn-lang"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
chumsky = { version = "0.10.1", features = ["pratt"] }
colored = "3.0.0"
logos = "0.15.0"
rustc-hash = "2.1.1"
slotmap = "1.0.7"
